// epcs_boot_tb - boot-loader unit cosim (Phase 5 + the Phase-7 second pass):
//
//   epcs_model (behavioural EPCS4, READ 0x03)  ->  epcs_boot (SPI master +
//   header/checksum parse, two passes)  ->  sdram_arbiter port 0  ->
//   sdram_ctrl  ->  behavioural sdram_model
//
// Default run: both real blobs (mem/boot_blob_flash.hex at 0x40000,
// mem/boot_blob11_flash.hex at 0x48000, generated by gen_boot_blob.py) are
// loaded into the flash model; after boot_done BOTH SDRAM regions (bk10 ROM
// at words 0x4000+, bk11 window-ROM banks + top ROM at 0x30000+) must equal
// the blob data word-for-word and boot_ok must be 1.
// +corrupt:  one data byte flipped in the FIRST blob  -> boot_ok = 0.
// +corrupt2: one data byte flipped in the SECOND blob -> boot_ok = 0, and the
//            bk10 region must still be word-exact (pass independence).
//
`timescale 1ns / 1ps

module epcs_boot_tb;

    localparam int AB = 24;
    localparam int DW = 16;
    localparam int NWORDS = 16320;

    reg sys_clk = 1'b0;
    always #5 sys_clk = ~sys_clk;

    reg [1:0] srst_sr = 2'b00;
    wire      srst_n  = srst_sr[1];
    always @(posedge sys_clk) srst_sr <= {srst_sr[0], 1'b1};

    // ---- flash + loader ------------------------------------------------------
    wire spi_dclk, spi_ncs, spi_mosi;
    tri1 spi_miso;                       // pulled up when the model tri-states

    epcs_model u_flash (
        .dclk(spi_dclk), .ncs(spi_ncs), .mosi(spi_mosi), .miso(spi_miso)
    );

    wire        bw_req, bw_gnt;
    wire [AB-1:0] bw_addr;
    wire [15:0]   bw_wdata;
    wire        boot_active, boot_done, boot_ok;
    wire        init_done;

    epcs_boot #(.ADDR_BITS(AB)) u_boot (
        .clk(sys_clk), .rst_n(srst_n), .start(init_done),
        .spi_dclk(spi_dclk), .spi_ncs(spi_ncs),
        .spi_mosi(spi_mosi), .spi_miso(spi_miso),
        .bw_req(bw_req), .bw_addr(bw_addr), .bw_wdata(bw_wdata), .bw_gnt(bw_gnt),
        .boot_active(boot_active), .boot_done(boot_done), .boot_ok(boot_ok)
    );

    // ---- arbiter port 0 (ports 1-3 idle) + controller + SDRAM model ----------
    localparam int NREQ = 4;
    wire [NREQ-1:0]    p_req    = {3'b000, bw_req};
    wire [NREQ-1:0]    p_we     = {3'b000, 1'b1};
    wire [NREQ*AB-1:0] p_addr   = {{(3*AB){1'b0}}, bw_addr};
    wire [NREQ*DW-1:0] p_wdata  = {{(3*DW){1'b0}}, bw_wdata};
    wire [NREQ*2-1:0]  p_be     = {6'b111111, 2'b11};
    wire [NREQ-1:0]    p_gnt, p_rvalid;
    assign bw_gnt = p_gnt[0];

    wire            cmd_req, cmd_we, cmd_ready, rd_valid;
    wire [AB-1:0]   cmd_addr;
    wire [DW-1:0]   cmd_wdata, rd_data, arb_rdata;
    wire [1:0]      cmd_be;

    sdram_arbiter #(.NREQ(NREQ), .ADDR_BITS(AB), .DQ_BITS(DW)) u_arb (
        .clk(sys_clk), .rst_n(srst_n),
        .p_req(p_req), .p_we(p_we), .p_addr(p_addr), .p_wdata(p_wdata), .p_be(p_be),
        .p_gnt(p_gnt), .p_rvalid(p_rvalid), .p_rdata(arb_rdata),
        .cmd_req(cmd_req), .cmd_we(cmd_we), .cmd_addr(cmd_addr),
        .cmd_wdata(cmd_wdata), .cmd_be(cmd_be), .cmd_ready(cmd_ready),
        .rd_valid(rd_valid), .rd_data(rd_data)
    );

    wire s_cke, s_cs_n, s_ras_n, s_cas_n, s_we_n;
    wire [1:0]  s_ba, s_dqm;
    wire [12:0] s_addr;
    wire [DW-1:0] dq_out, dq_in;  wire dq_oe;
    wire [DW-1:0] s_dq;
    assign s_dq  = dq_oe ? dq_out : 'z;
    assign dq_in = s_dq;

    sdram_ctrl #(.ADDR_BITS(AB), .DQ_BITS(DW)) u_ctrl (
        .clk(sys_clk), .rst_n(srst_n),
        .cmd_req(cmd_req), .cmd_we(cmd_we), .cmd_addr(cmd_addr),
        .cmd_wdata(cmd_wdata), .cmd_be(cmd_be), .cmd_ready(cmd_ready),
        .rd_valid(rd_valid), .rd_data(rd_data), .init_done(init_done),
        .s_cke(s_cke), .s_cs_n(s_cs_n), .s_ras_n(s_ras_n), .s_cas_n(s_cas_n),
        .s_we_n(s_we_n), .s_ba(s_ba), .s_addr(s_addr), .s_dqm(s_dqm),
        .dq_out(dq_out), .dq_oe(dq_oe), .dq_in(dq_in)
    );
    sdram_model u_mem (
        .clk(sys_clk), .cke(s_cke), .cs_n(s_cs_n), .ras_n(s_ras_n), .cas_n(s_cas_n),
        .we_n(s_we_n), .ba(s_ba), .addr(s_addr), .dqm(s_dqm), .dq(s_dq)
    );

    // ---- stimulus + check -----------------------------------------------------
    localparam int NWORDS11 = 40960;

    reg [7:0] blob [0:(1<<19)-1];        // reference copy of the flash bytes
    integer   ii, errors;
    reg [15:0] exp_word;

    // word-exact compare of one SDRAM region against the flash blob data
    task check_region(input [23:0] flash_base, input [23:0] sdram_base,
                      input integer nwords);
        begin
            for (ii = 0; ii < nwords; ii = ii + 1) begin
                exp_word = {blob[flash_base + 8 + 2*ii + 1],
                            blob[flash_base + 8 + 2*ii]};
                if (u_mem.mem[sdram_base + ii] !== exp_word) begin
                    if (errors < 10)
                        $display("EPCS-ERROR: word 0x%0h+%0d: sdram=%06o expected=%06o",
                                 sdram_base, ii, u_mem.mem[sdram_base + ii], exp_word);
                    errors = errors + 1;
                end
            end
        end
    endtask

    initial begin
        $readmemh("../mem/boot_blob_flash.hex",   u_flash.flash, 'h40000);
        $readmemh("../mem/boot_blob_flash.hex",   blob,          'h40000);
        $readmemh("../mem/boot_blob11_flash.hex", u_flash.flash, 'h48000);
        $readmemh("../mem/boot_blob11_flash.hex", blob,          'h48000);
        for (ii = 0; ii < (1<<18); ii = ii + 1) u_mem.mem[ii] = 16'hxxxx;

        if ($test$plusargs("corrupt")) begin
            // flip one bit of a data byte - the word checksum must catch it
            u_flash.flash['h40008 + 1234] = u_flash.flash['h40008 + 1234] ^ 8'h20;
        end
        if ($test$plusargs("corrupt2")) begin
            // same, in the second (bk11) blob
            u_flash.flash['h48008 + 1234] = u_flash.flash['h48008 + 1234] ^ 8'h20;
        end

        wait (boot_done);
        repeat (20) @(posedge sys_clk);

        errors = 0;
        if ($test$plusargs("corrupt")) begin
            if (boot_ok !== 1'b0) begin
                $display("EPCS-ERROR: corrupted blob but boot_ok=%b", boot_ok);
                errors = errors + 1;
            end
        end else if ($test$plusargs("corrupt2")) begin
            if (boot_ok !== 1'b0) begin
                $display("EPCS-ERROR: corrupted blob11 but boot_ok=%b", boot_ok);
                errors = errors + 1;
            end
            check_region('h40000, 'h4000, NWORDS);   // pass 0 unaffected
        end else begin
            if (boot_ok !== 1'b1) begin
                $display("EPCS-ERROR: boot_ok=%b after clean load", boot_ok);
                errors = errors + 1;
            end
            check_region('h40000, 'h4000,  NWORDS);
            check_region('h48000, 'h30000, NWORDS11);
        end

        if (errors == 0) $display("EPCS-BOOT: PASS");
        else             $display("EPCS-BOOT: FAIL (%0d errors)", errors);
        $finish;
    end

    initial begin
        #120_000_000;                    // 120 ms backstop (two-pass load ~77 ms)
        $display("EPCS-ERROR: timeout - boot_done never asserted");
        $display("EPCS-BOOT: FAIL");
        $finish;
    end

endmodule
