#!/usr/bin/env python3
"""Build the Phase-5 EPCS boot blob from the BK-0010.01 ROM set.

Input (mem/roms/, committed - BK ROMs are non-restricted for emulator use;
canonical source: the BkEmu project, app/src/main/res/raw/):
    monit10.rom    8192 B  @ BK 100000   (MONITOR)
    basic10_1.rom  8192 B  @ BK 120000   (BASIC Vilnius bank 1)
    basic10_2.rom  8192 B  @ BK 140000   (BASIC Vilnius bank 2)
    basic10_3.rom  8064 B  @ BK 160000   (BASIC Vilnius bank 3, ends at 177577)

Blob layout (stored at EPCS flash offset 0x40000, read by src/epcs_boot.sv):
    8-byte header:  u16 magic 0x4B42 ("BK"), u16 length in words (16320),
                    u16 checksum (16-bit sum of all data words), u16 zero
    32640 data bytes: file byte n -> BK byte 100000+n; SDRAM word 0x4000+n/2 =
                    {byte(n+1), byte(n)} (PDP-11 little-endian)
    All u16 fields little-endian (low byte first), same as the data words.

Outputs (gitignored, regenerated by make):
    boot_blob.bin        raw header+data (byte-compare reference for blob-check)
    boot_blob.hex        Intel HEX with every byte BIT-REVERSED - quartus_cpf
                         bit-reverses hex_block data pages when building the
                         EPCS POF (AS bitstreams are LSB-first; verified on
                         Quartus 11.0), so pre-reversing here makes the flash
                         hold the true bytes and the loader a plain MSB-first
                         SPI shift.
    boot_blob_flash.hex  one TRUE byte per line ($readmemh) - the flash-content
                         image for the behavioural sim/epcs_model.sv.
"""

import struct
import sys
from pathlib import Path

HERE = Path(__file__).parent
ROMS = [
    ("roms/monit10.rom",   8192, 0o100000),
    ("roms/basic10_1.rom", 8192, 0o120000),
    ("roms/basic10_2.rom", 8192, 0o140000),
    ("roms/basic10_3.rom", 8064, 0o160000),
]

MAGIC = 0x4B42          # "BK" little-endian on flash: 'B' 0x42, 'K' 0x4B


def bitrev8(b: int) -> int:
    return int(f"{b:08b}"[::-1], 2)


def intel_hex(data: bytes, reclen: int = 16) -> str:
    """Intel HEX at base address 0 (the flash offset comes from the COF)."""
    out = []
    for i in range(0, len(data), reclen):
        rec = data[i:i + reclen]
        if i > 0 and (i & 0xFFFF) == 0:          # extended linear address record
            upper = i >> 16
            line = bytes([2, 0, 0, 4, (upper >> 8) & 0xFF, upper & 0xFF])
            out.append(":" + (line + bytes([(-sum(line)) & 0xFF])).hex().upper())
        line = bytes([len(rec), (i >> 8) & 0xFF, i & 0xFF, 0]) + rec
        out.append(":" + (line + bytes([(-sum(line)) & 0xFF])).hex().upper())
    out.append(":00000001FF")
    return "\n".join(out) + "\n"


def main() -> None:
    data = bytearray()
    expect_addr = 0o100000
    for name, size, base in ROMS:
        raw = (HERE / name).read_bytes()
        assert len(raw) == size, f"{name}: {len(raw)} bytes, expected {size}"
        assert base == expect_addr, f"{name}: base {base:o}, expected {expect_addr:o}"
        data += raw
        expect_addr = base + size

    assert len(data) == 32640, len(data)
    assert expect_addr == 0o177600, oct(expect_addr)   # exactly fills to 177577

    words = struct.unpack(f"<{len(data)//2}H", bytes(data))
    assert words[0] == 0o000167, f"monit10 word0 {words[0]:06o} != 000167"
    checksum = sum(words) & 0xFFFF

    header = struct.pack("<HHHH", MAGIC, len(words), checksum, 0)
    blob = header + bytes(data)

    (HERE / "boot_blob.bin").write_bytes(blob)
    (HERE / "boot_blob.hex").write_text(intel_hex(bytes(bitrev8(b) for b in blob)))
    (HERE / "boot_blob_flash.hex").write_text(
        "".join(f"{b:02x}\n" for b in blob))

    # self-test: header + checksum round-trip out of the written .bin
    rb = (HERE / "boot_blob.bin").read_bytes()
    m, n, c, z = struct.unpack("<HHHH", rb[:8])
    rw = struct.unpack(f"<{n}H", rb[8:8 + 2 * n])
    assert (m, n, z) == (MAGIC, 16320, 0) and (sum(rw) & 0xFFFF) == c
    print(f"boot_blob: {len(blob)} bytes ({n} words), checksum {c:#06x} - OK")


if __name__ == "__main__":
    sys.exit(main())
