#!/usr/bin/env python3
"""Build the EPCS boot blobs: BK-0010.01 (Phase 5) + BK-0011M (Phase 7).

Input (mem/roms/, committed - BK ROMs are non-restricted for emulator use;
canonical source: the BkEmu project, app/src/main/res/raw/):
    monit10.rom    8192 B  @ BK 100000   (MONITOR)
    basic10_1.rom  8192 B  @ BK 120000   (BASIC Vilnius bank 1)
    basic10_2.rom  8192 B  @ BK 140000   (BASIC Vilnius bank 2)
    basic10_3.rom  8064 B  @ BK 160000   (BASIC Vilnius bank 3, ends at 177577)
and the BK-0011M set (mapping per BkEmu Computer.java configure(), 0011M arm):
    basic11m_0.rom 16384 B  window-1 ROM code 001 (whole 100000-137777)
    basic11m_1.rom  8192 B  window-1 ROM code 002, low half (100000-117777)
    ext11m.rom      8192 B  window-1 ROM code 002, high half (120000-137777)
    bos11m.rom      8192 B  fixed top ROM @ BK 140000 (BOS)
    mstd11m.rom     8192 B  fixed top ROM @ BK 160000 (MSTD, stock config)
and the SMK512 BIOS (Phase 8; BkEmu res/raw/disk_smk512_v205.rom):
    smk512_v205.rom 4096 B  ONE 4 KB image backing BOTH selectable windows
                            (rom6 @ BK 160000, rom7 @ BK 170000; selection
                            per SMK mode in mem_mapper)

Blob format (shared; read by the two-pass src/sdram/epcs_boot.sv):
    8-byte header:  u16 magic 0x4B42 ("BK"), u16 length in words,
                    u16 checksum (16-bit sum of all data words), u16 zero
    then the data bytes; all u16 fields little-endian (low byte first),
    same as the data words (PDP-11 word order).

bk10 blob (flash 0x40000 -> SDRAM words 0x4000+, 16320 words):
    file byte n -> BK byte 100000+n; SDRAM word 0x4000+n/2 = {byte(n+1), byte(n)}
bk11 blob (flash 0x48000 -> SDRAM words 0x30000+, 43008 words, contiguous):
    0x30000  basic11m_0              (window-1 ROM bank 0, code 001)
    0x32000  basic11m_1 + ext11m     (bank 1, code 002)
    0x34000  16384 B of 0x00 filler  (bank 2, code 010 - unpopulated socket;
    0x36000  16384 B of 0x00 filler   bank 3, code 020; word 000000 = HALT)
    0x38000  bos11m                  (fixed top ROM, BK 140000)
    0x39000  mstd11m                 (BK 160000; the last 0x40 words land at
             BK 177600+ which the mapper never serves - kept for contiguity)
    0x3A000  smk512_v205             (SMK BIOS = mem_mapper SMK_BIOS_BASE; the
             word at image byte offset 0o7716 is the SYS-mode boot vector the
             CPU reads through the 177716 register-space overlay - see the
             asserts below)

Outputs (gitignored, regenerated by make):
    boot_blob.bin        raw header+data (reference for blob-check)
    boot_blob.hex        Intel HEX with the TRUE bytes. Bit-order chain
                         (verified on hardware + Quartus 11.0): quartus_cpf
                         bit-reverses hex_block bytes into the POF/RPD (the
                         RPD is in RBF/LSB-first bit order, NOT physical), and
                         quartus_pgm -m AS bit-reverses again when programming
                         the EPCS - the two cancel, so the PHYSICAL flash holds
                         these bytes verbatim as seen by an MSB-first SPI READ.
                         (First attempt pre-reversed here and the loader read
                         rev(blob) on real hardware - magic check failed.)
    boot_blob_flash.hex  one byte per line ($readmemh) - the physical-flash
                         image for the behavioural sim/epcs_model.sv (identical
                         byte values to the blob, by the above).
    boot_blob11.bin / boot_blob11.hex / boot_blob11_flash.hex
                         the same three for the bk11 blob.
"""

import struct
import sys
from pathlib import Path

HERE = Path(__file__).parent
ROMS = [
    ("roms/monit10.rom",   8192, 0o100000),
    ("roms/basic10_1.rom", 8192, 0o120000),
    ("roms/basic10_2.rom", 8192, 0o140000),
    ("roms/basic10_3.rom", 8064, 0o160000),
]

# BK-0011M set: (file, size) in bk11-blob order; None = zero filler.
ROMS11 = [
    ("roms/basic11m_0.rom", 16384),   # bank 0 (code 001)
    ("roms/basic11m_1.rom",  8192),   # bank 1 (code 002) low
    ("roms/ext11m.rom",      8192),   # bank 1 (code 002) high
    (None,                  16384),   # bank 2 (code 010) - empty socket
    (None,                  16384),   # bank 3 (code 020) - empty socket
    ("roms/bos11m.rom",      8192),   # top ROM 140000 (BOS)
    ("roms/mstd11m.rom",     8192),   # top ROM 160000 (MSTD)
    ("roms/smk512_v205.rom", 4096),   # SMK512 BIOS (rom6/rom7 windows)
]

MAGIC = 0x4B42          # "BK" little-endian on flash: 'B' 0x42, 'K' 0x4B


def intel_hex(data: bytes, reclen: int = 16) -> str:
    """Intel HEX at base address 0 (the flash offset comes from the COF)."""
    out = []
    for i in range(0, len(data), reclen):
        rec = data[i:i + reclen]
        if i > 0 and (i & 0xFFFF) == 0:          # extended linear address record
            upper = i >> 16
            line = bytes([2, 0, 0, 4, (upper >> 8) & 0xFF, upper & 0xFF])
            out.append(":" + (line + bytes([(-sum(line)) & 0xFF])).hex().upper())
        line = bytes([len(rec), (i >> 8) & 0xFF, i & 0xFF, 0]) + rec
        out.append(":" + (line + bytes([(-sum(line)) & 0xFF])).hex().upper())
    out.append(":00000001FF")
    return "\n".join(out) + "\n"


def write_blob(stem: str, data: bytes, nwords: int) -> None:
    """Header + data -> .bin / .hex / _flash.hex, with a round-trip self-test."""
    words = struct.unpack(f"<{len(data)//2}H", data)
    checksum = sum(words) & 0xFFFF
    blob = struct.pack("<HHHH", MAGIC, len(words), checksum, 0) + data

    (HERE / f"{stem}.bin").write_bytes(blob)
    (HERE / f"{stem}.hex").write_text(intel_hex(blob))
    (HERE / f"{stem}_flash.hex").write_text(
        "".join(f"{b:02x}\n" for b in blob))

    # self-test: header + checksum round-trip out of the written .bin
    rb = (HERE / f"{stem}.bin").read_bytes()
    m, n, c, z = struct.unpack("<HHHH", rb[:8])
    rw = struct.unpack(f"<{n}H", rb[8:8 + 2 * n])
    assert (m, n, z) == (MAGIC, nwords, 0) and (sum(rw) & 0xFFFF) == c
    print(f"{stem}: {len(blob)} bytes ({n} words), checksum {c:#06x} - OK")


def main() -> None:
    # ---- bk10 blob (Phase 5) ------------------------------------------------
    data = bytearray()
    expect_addr = 0o100000
    for name, size, base in ROMS:
        raw = (HERE / name).read_bytes()
        assert len(raw) == size, f"{name}: {len(raw)} bytes, expected {size}"
        assert base == expect_addr, f"{name}: base {base:o}, expected {expect_addr:o}"
        data += raw
        expect_addr = base + size

    assert len(data) == 32640, len(data)
    assert expect_addr == 0o177600, oct(expect_addr)   # exactly fills to 177577

    words = struct.unpack(f"<{len(data)//2}H", bytes(data))
    assert words[0] == 0o000167, f"monit10 word0 {words[0]:06o} != 000167"
    write_blob("boot_blob", bytes(data), 16320)

    # ---- bk11 blob (Phase 7) ------------------------------------------------
    data11 = bytearray()
    for name, size in ROMS11:
        raw = (HERE / name).read_bytes() if name else bytes(size)
        assert len(raw) == size, f"{name}: {len(raw)} bytes, expected {size}"
        data11 += raw

    assert len(data11) == 86016, len(data11)           # 43008 words, 0x30000-0x3A7FF
    w11 = struct.unpack(f"<{len(data11)//2}H", bytes(data11))
    assert w11[0x0000] == 0o010103, f"basic11m_0 word0 {w11[0]:06o} != 010103"
    assert w11[0x8000] == 0o106427, f"bos11m word0 {w11[0x8000]:06o} != 106427"
    assert w11[0x9000] == 0o000240, f"mstd11m word0 {w11[0x9000]:06o} != 000240"
    assert w11[0xA000] == 0o000410, f"smk bios word0 {w11[0xA000]:06o} != 000410"
    # The load-bearing SMK boot word: in SYS mode the rom7 window overlays the
    # register space, so the CPU's initial-start 177716 read returns this word
    # (OR-ed with SEL1) and PC <- value & 0o177400 = 166400, inside rom6.
    boot_w = w11[0xA000 + (0o7716 >> 1)]
    assert boot_w == 0o166400, f"smk bios 177716 word {boot_w:06o} != 166400"
    write_blob("boot_blob11", bytes(data11), 43008)


if __name__ == "__main__":
    sys.exit(main())
